### ISSUE TITLE
Enhancement : Add autoscaling for ecs and make that optional

### ISSUE THREAD

**Issue by mayank0202** [sourcefuse/terraform-aws-arc-ecs#53]
We propose enhancing our ECS (Elastic Container Service) setup by adding autoscaling capabilities while also making it optional. Autoscaling can dynamically adjust resources based on demand, improving efficiency and responsiveness. However, offering it as an optional feature allows users to maintain control over resource management according to their specific requirements and preferences.

**Autoscaling Functionality:**  Implement autoscaling policies that adjust the number of ECS tasks or services based on metrics such as CPU or memory utilization, request count, or custom metrics.

**Optional Configuration:** Introduce a configuration option to enable or disable autoscaling, providing flexibility for users to choose their preferred resource management approach.

**Configuration Management:** Ensure that enabling or disabling autoscaling is straightforward and doesn't require extensive modifications to the ECS setup.

**Monitoring and Alerts:** Implement monitoring for ECS cluster and autoscaling activities, allowing administrators to track scaling events and receive alerts for any issues.

**Comment by asthamalhotra** [comment]
@jamescrowley321 @mayank0202 I am using this module and if possible please add autoscaling functionality
