### ISSUE TITLE
Add autoscaling support

### ISSUE THREAD

**Issue by tsaucier-sf** [sourcefuse/terraform-aws-arc-ecs#61]
**Is your feature request related to a problem? Please describe.**
There are instances where we would like to enable autoscaling on the deployed Fargate resources. This module should support that feature, since it manages the ECS cluster. 

**Describe the solution you'd like**
Add Fargate Autoscaling as an optional input.

**Comment by mayank0202** [comment]
@tsaucier-sf  we add autoscaling for ecs services and by default we only have default health check service so do you think we should add autoscaling here or have another repo for autoscaling ? cc: @jamescrowley321

**Comment by tsaucier-sf** [comment]
Requirement satisfied.

**Comment by jamescrowley321** [comment]
@tsaucier-sf @mayank0202 Let's provide info on how to do it. Closing the issue wtihout guidance doesn't help the OP.

**Comment by mayank0202** [comment]
Where we can provide the info? README ?

**Comment by jamescrowley321** [comment]
Docs site is probably best.

**Comment by mayank0202** [comment]
Okay i will create an github issue for adding docs

**Comment by mayank0202** [comment]
https://github.com/sourcefuse/arc-docs/issues/101

FYI
